# Generated by Django 6.0.4 on 2026-04-14 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_fantasia", models.CharField(max_length=200)),
                ("razao_social", models.CharField(blank=True, max_length=200)),
                (
                    "cnpj",
                    models.CharField(max_length=18, unique=True, verbose_name="CNPJ"),
                ),
                ("contato", models.CharField(blank=True, max_length=100)),
                ("telefone", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "secretaria",
                    models.CharField(
                        max_length=200, verbose_name="Secretaria Solicitante"
                    ),
                ),
                ("data_pedido", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SOLICITADO", "Solicitado"),
                            ("RESERVADO", "Reservado"),
                            ("EMPENHADO", "Empenhado"),
                            ("ENTREGUE", "Entregue"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="SOLICITADO",
                        max_length=20,
                    ),
                ),
                (
                    "empenho_anexo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="empenhos/",
                        verbose_name="Anexo de Empenho",
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Pedido",
                "verbose_name_plural": "Pedidos",
            },
        ),
        migrations.CreateModel(
            name="Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_entrada", models.DateField(auto_now_add=True)),
                (
                    "numero_nota",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número da Nota"
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "fornecedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entradas",
                        to="estoque.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entrada",
                "verbose_name_plural": "Entradas",
            },
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                (
                    "unidade_medida",
                    models.CharField(
                        choices=[
                            ("UN", "Unidade"),
                            ("CX", "Caixa"),
                            ("KG", "Quilo"),
                            ("LT", "Litro"),
                            ("PCT", "Pacote"),
                            ("RM", "Resma"),
                        ],
                        default="UN",
                        max_length=3,
                    ),
                ),
                (
                    "estoque_atual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estoque_reservado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "estoque_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="produtos",
                        to="estoque.categoria",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
            },
        ),
        migrations.CreateModel(
            name="ItemPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.pedido",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Pedido",
                "verbose_name_plural": "Itens de Pedido",
            },
        ),
        migrations.CreateModel(
            name="ItemEntrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantidade", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "preco_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço Unitário"
                    ),
                ),
                (
                    "entrada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itens",
                        to="estoque.entrada",
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item de Entrada",
                "verbose_name_plural": "Itens de Entrada",
            },
        ),
    ]
