# Generated by Django 6.0.4 on 2026-04-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="itempedido",
            name="preco_unitario",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Preço Unit."
            ),
        ),
        migrations.AddField(
            model_name="itempedido",
            name="quantidade_atendida",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Qt. Atendida"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="compra_direta",
            field=models.BooleanField(default=False, verbose_name="Compra Direta?"),
        ),
        migrations.AddField(
            model_name="pedido",
            name="endereco_entrega",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Endereço de Entrega"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="fornecedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pedidos",
                to="estoque.fornecedor",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="licitacao",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Licitação/Contrato"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="numero_empenho",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="Nº Empenho"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="programa",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Programa/Convênio"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="setor",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="Setor/Departamento"
            ),
        ),
        migrations.AlterField(
            model_name="itempedido",
            name="quantidade",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Qt. Pedida"
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data_pedido",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="observacoes",
            field=models.TextField(blank=True, verbose_name="Observação"),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="secretaria",
            field=models.CharField(max_length=200, verbose_name="Unidade/Secretaria"),
        ),
    ]
