# Generated by Django 6.0.4 on 2026-04-16 16:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_itempedido_preco_unitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='compra_direta',
            field=models.BooleanField(default=False, verbose_name='Compra Direta?'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='licitacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Licitação'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='lote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lote'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='numero_empenho',
            field=models.CharField(blank=True, max_length=50, verbose_name='Nº Empenho'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='numero_pedido',
            field=models.CharField(blank=True, max_length=50, verbose_name='Núm. Pedido'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='programa',
            field=models.CharField(blank=True, max_length=100, verbose_name='Programa'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='setor',
            field=models.CharField(blank=True, max_length=200, verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='unidade',
            field=models.CharField(blank=True, max_length=200, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='itementrada',
            name='licitacao_restante',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Licit. Rest.'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='quantidade_licitada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Qt. Licitada'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='data_entrada',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
