# Generated by Django 6.0.4 on 2026-04-17 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0007_unidade_setor_relacionamentos"),
    ]

    operations = [
        migrations.AddField(
            model_name="setor",
            name="cargo_representante",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Cargo do Representante",
            ),
        ),
        migrations.AddField(
            model_name="setor",
            name="representante",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Representante"
            ),
        ),
        migrations.AddField(
            model_name="unidade",
            name="cargo_representante",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="Cargo do Representante",
            ),
        ),
        migrations.AddField(
            model_name="unidade",
            name="representante",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Representante"
            ),
        ),
    ]
