# Generated by Django 6.0.4 on 2026-05-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_entrada_criado_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='licitacao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Licitação/Contrato'),
        ),
    ]
