services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-almoxarifado}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    volumes:
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    # networks:
    #   - almoxarifado_network

  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME:-almoxarifado}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres} -d $${POSTGRES_DB:-almoxarifado}"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - almoxarifado_network

volumes:
  postgres_data:
  media_volume:

# networks:
#   almoxarifado_network:
#     driver: bridge
