services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: almoxarifado_app
    restart: always
    environment:
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    volumes:
      - media_volume:/app/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - almoxarifado_network

  db:
    image: postgres:17-alpine
    container_name: almoxarifado_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - almoxarifado_network

volumes:
  postgres_data:
  media_volume:

networks:
  almoxarifado_network:
    driver: bridge
